### ISSUE TITLE
此課程尚未使用class哦

### ISSUE THREAD

**Issue by Sean-fn** [cutelearn/crawler#1]

**Comment by yang-lin94** [comment]
我知道 但老師不會管你怎麼寫 只要你可以解釋就好

**Comment by Sean-fn** [comment]
# 學校規定
基本上這些程式碼還是要依照學校的規定去算成績的，再麻煩修復
👍 do not use classes:`class Name():`

**Comment by yang-lin94** [comment]
這邊有管道可以申請複查，且有通過教師的認證，所以是可以的喔。
